 /* Tables should be added individually (to prevent error) */

CREATE TABLE GAMER(
   USERNAME  VARCHAR(50) NOT NULL,
   PASSWORD VARCHAR(50) NOT NULL,
   FIRSTNAME VARCHAR(50) NOT NULL,
   LASTNAME VARCHAR(50) NOT NULL,
   EMAIL VARCHAR(50) NOT NULL,
   PRIMARY KEY (USERNAME)
);

 
CREATE TABLE "CHARACTER" (
   CHARACTER_NAME  VARCHAR(50) NOT NULL,
   "LEVEL" VARCHAR(50) NOT NULL,
   EXP VARCHAR(50) NOT NULL,
   HP VARCHAR(50) NOT NULL,
   MP VARCHAR(50) NOT NULL,
   STRENGTH VARCHAR(50) NOT NULL,
   INTELLIGENCE VARCHAR(50) NOT NULL,
   DEXTERITY VARCHAR(50) NOT NULL,
   "CLASS" VARCHAR(50) NOT NULL,
   USERNAME VARCHAR(50) NOT NULL,
   PRIMARY KEY (CHARACTER_NAME),
   FOREIGN KEY (USERNAME) REFERENCES GAMER(USERNAME)
);


CREATE TABLE PVP_MATCH (
   MATCHID  VARCHAR(50) NOT NULL,
   WINNER_NAME VARCHAR(50) NOT NULL,
   LOSER_NAME VARCHAR(50) NOT NULL,
   KILL_TIME VARCHAR(50) NOT NULL,
   KILL_SCORE VARCHAR(50) NOT NULL
);


CREATE TABLE GUILD (
   GUILD_NAME  VARCHAR(50) NOT NULL,
   FOUNDING_TIME VARCHAR(50) NOT NULL,
   STATUS VARCHAR(50) NOT NULL,
   PRIMARY KEY (GUILD_NAME)
);


CREATE TABLE CHARACTER_GUILD (
   GUILD_NAME  VARCHAR(50) NOT NULL,
   CHARACTER_NAME VARCHAR(50) NOT NULL,
   PRIMARY KEY (GUILD_NAME, CHARACTER_NAME),
   FOREIGN KEY (CHARACTER_NAME) REFERENCES "CHARACTER"(CHARACTER_NAME),
   FOREIGN KEY (GUILD_NAME) REFERENCES GUILD(GUILD_NAME)
);



CREATE TABLE ITEM (
   ITEM_NAME  VARCHAR(50) NOT NULL,
   "VALUE" VARCHAR(50) NOT NULL,
   STATUS VARCHAR(50) NOT NULL,
   "TYPE" VARCHAR(50) NOT NULL,
   PRIMARY KEY (ITEM_NAME)
);


CREATE TABLE ARMOR (
   ITEM_NAME  VARCHAR(50) NOT NULL,
   DEFENSE VARCHAR(50) NOT NULL,
   "TYPE" VARCHAR(50) NOT NULL,
   PRIMARY KEY (ITEM_NAME),
   FOREIGN KEY (ITEM_NAME) REFERENCES ITEM(ITEM_NAME)
);


CREATE TABLE ACCESSORY (
   ITEM_NAME  VARCHAR(50) NOT NULL,
   SPECIAL_EFFECTS VARCHAR(50) NOT NULL,
   "TYPE" VARCHAR(50) NOT NULL,
   PRIMARY KEY (ITEM_NAME),
   FOREIGN KEY (ITEM_NAME) REFERENCES ITEM(ITEM_NAME)
);


CREATE TABLE WEAPON (
   ITEM_NAME  VARCHAR(50) NOT NULL,
   SPEED VARCHAR(50) NOT NULL,
   DPS VARCHAR(50) NOT NULL,
   PRIMARY KEY (ITEM_NAME),
   FOREIGN KEY (ITEM_NAME) REFERENCES ITEM(ITEM_NAME)
);


CREATE TABLE CHARACTER_ITEM (
   CHARACTER_NAME  VARCHAR(50) NOT NULL,
   ITEM_NAME VARCHAR(50) NOT NULL,
   PRIMARY KEY (CHARACTER_NAME, ITEM_NAME),
   FOREIGN KEY (ITEM_NAME) REFERENCES ITEM(ITEM_NAME),
   FOREIGN KEY (CHARACTER_NAME) REFERENCES "CHARACTER"(CHARACTER_NAME)
);


CREATE TABLE SKILL (
   SKILL_ID  VARCHAR(50) NOT NULL,
   "NAME" VARCHAR(50) NOT NULL,
   MPCOST VARCHAR(50) NOT NULL,
   "LEVEL" VARCHAR(50) NOT NULL,
   DESCRIPTION VARCHAR(50) NOT NULL,
   PRIMARY KEY (SKILL_ID)
   );
   
   
CREATE TABLE CHARACTER_SKILL (
   CHARACTER_NAME  VARCHAR(50) NOT NULL,
   "NAME" VARCHAR(50) NOT NULL,
   SKILL_ID VARCHAR(50) NOT NULL,
   PRIMARY KEY (CHARACTER_NAME, SKILL_ID),
   FOREIGN KEY (SKILL_ID) REFERENCES SKILL(SKILL_ID),
   FOREIGN KEY (CHARACTER_NAME) REFERENCES "CHARACTER"(CHARACTER_NAME)
);


CREATE TABLE PREREQUISITE_SKILL (
   SKILL_ID  VARCHAR(50) NOT NULL,
   PREREQUISITE_SKILL_ID VARCHAR(50) NOT NULL,
   PRIMARY KEY (SKILL_ID, PREREQUISITE_SKILL_ID),
   FOREIGN KEY (SKILL_ID) REFERENCES SKILL(SKILL_ID)
);
